---
- name: install nomad
  hosts:
    "{{ variable_host }}"    
    #     - worker-4

  tasks:
    - name: install yum-utils
      become: true
      ansible.builtin.shell: "yum install -y yum-utils"

    - name: update repo hashicorp
      become: true
      ansible.builtin.shell: "yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo"

    - name: install nomad
      become: true
      ansible.builtin.shell: "yum install -y nomad"

