---
name: "disk_full"
pack: "certademo"
description: "disk full"
enabled: false

trigger:
  type: "core.st2.webhook"
  parameters:
    url: "certademo"

criteria:
  trigger.body.alerts[0].labels.alertname:
    pattern: "HostOutOfDiskSpace"
    type: "equals"
  trigger.body.alerts[0].status:
    pattern: "firing"
    type: "equals"

action:
  ref: "certademo.disk_full"
  parameters:
    instance: "{{trigger.body.alerts[0].labels.instance}}"
    mountpoint: "{{trigger.body.alerts[0].labels.mountpoint}}"
    # message: |
    #   status: {{trigger.body.alerts[0].status}}
    #   severity: {{trigger.body.alerts[0].labels.severity}}
    #   hostip: {{trigger.body.alerts[0].labels.instance}}
    #   hostname: {{trigger.body.alerts[0].labels.nodename}}
    #   startsAt: {{trigger.body.alerts[0].startsAt}}
    #   endsAt: {{trigger.body.alerts[0].endsAt}}
    #   description: {{trigger.body.alerts[0].annotations.description}}
    #   summary: {{trigger.body.alerts[0].annotations.summary}}
