---
name: "drain_node"
pack: "certademo"
description: "nomad node drain"
enabled: true

trigger:
  type: "core.st2.webhook"
  parameters:
    url: "certademo"

criteria:
  trigger.body.alerts[0].labels.alertname:
    pattern: "NodeDrain_rv03"
    type: "equals"
  trigger.body.alerts[0].status:
    pattern: "firing"
    type: "equals"

# action:
#   ref: "certademo.apache_down"
#   parameters:
#     hostip: "{{trigger.body.alerts[0].labels.instance}}"

action:
  ref: "chatops.post_message"
  parameters:
    channel: "stackstorm-demo"
    message: |
      {{trigger.body}}