---
name: "newticket_jirav2"
pack: "certademo"
description: "handle if there is new ticket created from jira API v2"
enabled: true

trigger:
  type: "jira.issues_tracker_for_apiv2"

criteria: {}

action:
  ref: "chatops.post_message"
  parameters:
    channel: "stackstorm-demo"
    message: |
      Receive new ticket from jira
      Trigger issue key: {{trigger.issue_key}}
      Trigger url: {{trigger.issue_url}}
      Browse url: {{trigger.issue_browse_url}}
      Issue Type: {{trigger.fields.issuetype.name}}
      Issue Type description: {{trigger.fields.issuetype.description}}
      Issue Summary: {{trigger.fields.summary}}